server:
  port: 8003
spring:
  application:
    name: cloud-forum-service
  datasource:
    # 当前数据源操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    # mysql驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://1.15.156.161:3306/cluboat_test?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    username: cluboat
    password: esY4WkpBczwTZPhs
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      routes:
        - id: forum-service # 路由id，自定义，只要唯一即可
          # uri: http://127.0.0.1:8081 # 路由的目标地址 http就是固定地址
          uri: lb://forumservice # 路由的目标地址 lb就是负载均衡，后面跟服务名称
          predicates: # 路由断言，也就是判断请求是否符合路由规则的条件
            - Path=/forum/** # 这个是按照路径匹配，只要以/forum/开头就符合要求
logging:
  pattern:
    console: "[%thread] %-5level %logger{36} - %msg%n"



