server:
  port: 8105
spring:
  application:
    name: cloud-forum-service-se
  datasource:
    # 当前数据源操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    # mysql驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://1.15.156.161:3306/cluboat_new?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    username: CluBoat
    password: zeaCMsNTSprifxER
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
logging:
  pattern:
    console: "[%thread] %-5level %logger{36} - %msg%n"



